title: yjh's Homepage
page-top-title: yjh
top-section-bg-text: 不必为将来的成就莫名焦虑，只要认真过好今天这一天，自然就能看清明天。这样日复一日，五年、十年以后，就会结出巨大的果实。
home-subtitle: yjh&ensp;|&ensp;yjh
copyright-text: ' yjh 2023-2025. All Rights Reserved.'
